[package]
name = "aether_service"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aether_lib = "0.1.1"
log = "0.4.17"
simple_logger = "2.1.0"
